apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: local-ai-librechat
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/local-ai/mongodb
    type: DirectoryOrCreate
