apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: local-ai
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: local-ai-librechat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: mongodb-pv
  resources:
    requests:
      storage: 10Gi
