apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-chat-models
  namespace: local-ai
  labels:
    app.kubernetes.io/name: llm-chat
    app.kubernetes.io/part-of: local-ai-librechat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 8Gi
