apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-yaml
  namespace: local-ai
  labels:
    app.kubernetes.io/name: librechat
    app.kubernetes.io/part-of: local-ai-librechat
data:
  librechat.yaml: |
    version: 1.2.8
    cache: true
    endpoints:
      custom:
        - name: "Local LLM"
          apiKey: "not-needed"
          baseURL: "http://llm-chat:8080/v1"
          models:
            default: ["local-model"]
            fetch: true
          titleConvo: true
          titleModel: "current_model"
          modelDisplayLabel: "Local LLM"
