apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librechat-pvc
  namespace: local-ai
  labels:
    app.kubernetes.io/name: librechat
    app.kubernetes.io/part-of: local-ai-librechat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
